//
//  Screen2Interactor.swift
//  tab bar controller implementation
//
//  Created by Kanaan Zafar on 07/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Screen2BusinessLogic
{
  func doSomething(request: Screen2.Something.Request)
}

protocol Screen2DataStore
{
  //var name: String { get set }
}

class Screen2Interactor: Screen2BusinessLogic, Screen2DataStore
{
  var presenter: Screen2PresentationLogic?
  var worker: Screen2Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Screen2.Something.Request)
  {
    worker = Screen2Worker()
    worker?.doSomeWork()
    
    let response = Screen2.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
