//
//  Screen4Interactor.swift
//  tab bar controller implementation
//
//  Created by Kanaan Zafar on 07/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Screen4BusinessLogic
{
  func doSomething(request: Screen4.Something.Request)
}

protocol Screen4DataStore
{
  //var name: String { get set }
}

class Screen4Interactor: Screen4BusinessLogic, Screen4DataStore
{
  var presenter: Screen4PresentationLogic?
  var worker: Screen4Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Screen4.Something.Request)
  {
    worker = Screen4Worker()
    worker?.doSomeWork()
    
    let response = Screen4.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
