//
//  Screen1Interactor.swift
//  tab bar controller implementation
//
//  Created by Kanaan Zafar on 07/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Screen1BusinessLogic
{
  func doSomething(request: Screen1.Something.Request)
}

protocol Screen1DataStore
{
  //var name: String { get set }
}

class Screen1Interactor: Screen1BusinessLogic, Screen1DataStore
{
  var presenter: Screen1PresentationLogic?
  var worker: Screen1Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Screen1.Something.Request)
  {
    worker = Screen1Worker()
    worker?.doSomeWork()
    
    let response = Screen1.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
