//
//  Screen3Interactor.swift
//  tab bar controller implementation
//
//  Created by Kanaan Zafar on 07/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Screen3BusinessLogic
{
  func doSomething(request: Screen3.Something.Request)
}

protocol Screen3DataStore
{
  //var name: String { get set }
}

class Screen3Interactor: Screen3BusinessLogic, Screen3DataStore
{
  var presenter: Screen3PresentationLogic?
  var worker: Screen3Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Screen3.Something.Request)
  {
    worker = Screen3Worker()
    worker?.doSomeWork()
    
    let response = Screen3.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
