//
//  Screen5Interactor.swift
//  tab bar controller implementation
//
//  Created by Kanaan Zafar on 07/09/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Screen5BusinessLogic
{
  func doSomething(request: Screen5.Something.Request)
}

protocol Screen5DataStore
{
  //var name: String { get set }
}

class Screen5Interactor: Screen5BusinessLogic, Screen5DataStore
{
  var presenter: Screen5PresentationLogic?
  var worker: Screen5Worker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Screen5.Something.Request)
  {
    worker = Screen5Worker()
    worker?.doSomeWork()
    
    let response = Screen5.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
